[package]
name = "synth"
description = "Basic synth made from scratch"
version = "0.1.0"
authors = ["HectorxH"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
cpal = "0.15.2"
crossbeam-channel = "0.5.8"
dasp = "0.11.0"
